# config/initializers/config.rb
# this file is generated by Orchid

CONFIG = YAML.load_file("#{Rails.root}/config/config.yml")[Rails.env]

VERSION = CONFIG["version"]

API_PATH = CONFIG["api_path"]
API_OPTS = CONFIG["api_opts"]

DATE_FIRST = CONFIG["date_first"] || ["1800", "01", "01"]
DATE_LAST = CONFIG["date_last"] || ["1900", "12", "31"]

def date_display date_arr
  DateTime.new(
    date_arr[0].to_i,
    date_arr[1].to_i,
    date_arr[2].to_i
  ).strftime("%b %d, %Y")
end

DATE_DISPLAY_FIRST = date_display DATE_FIRST
DATE_DISPLAY_LAST = date_display DATE_LAST
